### ISSUE TITLE
orm module cannot be imported

### ISSUE THREAD

**Issue by tobinmori** [socialwifi/jsonapi-requests#18] opened 2017-04-11 14:37 UTC
Add this to jsonapi_requests/__init__.py:

```
from .orm import OrmApi

__all__ = [Api, JsonApiObject, OrmApi]
```

**Comment by kramarz** [comment] 2017-04-14 07:50
I can't reproduce this issue.  Can You explain whats wrong? which python do you use?
```
$ python -c 'from jsonapi_requests import orm; print(orm.OrmApi)' 
<class 'jsonapi_requests.orm.api.OrmApi'>
$ python -c 'from jsonapi_requests.orm import OrmApi; print(OrmApi)' 
<class 'jsonapi_requests.orm.api.OrmApi'>
$ python -c 'import jsonapi_requests.orm; print(jsonapi_requests.orm.OrmApi)' 
<class 'jsonapi_requests.orm.api.OrmApi'>
```

**Comment by evandavey** [comment] 2017-04-14 08:26
```
$ python -c 'import jsonapi_requests; print(jsonapi_requests.orm.OrmApi)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'jsonapi_requests' has no attribute 'orm'
```

**Comment by kramarz** [comment] 2017-04-14 12:27
I will add
```
from . import orm

__all__ = [Api, JsonApiObject, orm]
```
I don't want to have Api and OrmApi in one namespace. We may in future change which will be in root namespace, but for now OrmApi is very limited.

**Closed** 2017-04-19 07:58 UTC
